### Login (dapatkan token)
POST http://127.0.0.1:8000/api/login
Content-Type: application/json

{
  "username": "admin",
  "password": "pastibisa"
}

### Logout
POST http://127.0.0.1:8000/api/logout
Authorization: Bearer 2|7223KYAITFJ6h4uoIxDALqFvI3FhCoa6J62Ef0ob69acb037
